#!/usr/bin/env php
<?php

/**
 * Autoload.
 */

require_once __DIR__ .'/vendor/autoload.php';

/**
 * Start the app.
 */
$app = app();

/**
 * Set the connection for the app.
 */
$app->setConnection(
    new Framework\Connection(
        config('db.name', 'mvc'),
        config('db.host', 'db'),
        config('db.user', 'root'),
        config('db.password', 'root')
    )
);

$commandsNamespace = 'App\\Commands\\';

if (count($argv) < 2) {
    echo "Missing command. Example: php command {command} {...args}\n";
    return;
}

try {
    $args = count($argv) ? array_slice($argv, 2) : null;
    $reflection = new ReflectionClass($commandsNamespace . $argv[1]);
    $command = $reflection->newInstance($args);
    $method = $reflection->getMethod('handle');
    $method->invoke($command, $args);
} catch (ReflectionException $e) {
    echo "Command not found. ($commandsNamespace" . "$argv[1]) \n";
}